language: perl6

os:
  - linux
  - osx

perl6:
  - latest

sudo: false

install:
  - rakudobrew build zef
  - zef --verbose build .

script:
  - AUTHOR_TESTING=1 prove -ve "perl6 -Ilib"
  - zef --verbose install .
