language: perl6

os:
  - linux
  - osx

perl6:
  - latest

sudo: false

install:
  - rakudobrew build zef
  - zef --verbose build .

script:
  - echo "ABOUT TO RUN TESTS!!! $TRAVIS_BUILD_DIR $DYLD_FALLBACK_LIBRARY_PATH $PWD"
  - ls -ltr $TRAVIS_BUILD_DIR/resources/lib
  - AUTHOR_TESTING=1 prove -ve "perl6 -Ilib"
  - zef --verbose install .
